name: Minikube Integration Tests - blue-green ingress
on:
   pull_request:
      branches:
         - main
         - 'releases/*'
   push:
      branches:
         - main
         - 'releases/*'
   workflow_dispatch:

permissions: {}

jobs:
   run-integration-test:
      name: Blue-Green Ingress Tests
      runs-on: ubuntu-22.04
      permissions:
         contents: read
      env:
         KUBECONFIG: /home/runner/.kube/config
         NAMESPACE: test-${{ github.run_id }}
      steps:
         - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

         - uses: ./.github/actions/minikube-setup
           name: Setup Minikube Environment
           timeout-minutes: 5

         - name: Create namespace to run tests
           env:
              NS: ${{ env.NAMESPACE }}
           run: kubectl create ns "$NS"

         - name: Cleaning any previously created items
           env:
              NS: ${{ env.NAMESPACE }}
           run: |
              python test/integration/k8s-deploy-delete.py 'Service' 'nginx-service' "$NS"
              python test/integration/k8s-deploy-delete.py 'Service' 'nginx-service-green' "$NS"
              python test/integration/k8s-deploy-delete.py 'Deployment' 'nginx-deployment-green' "$NS"
              python test/integration/k8s-deploy-delete.py 'Deployment' 'nginx-deployment' "$NS"
              python test/integration/k8s-deploy-delete.py 'Ingress' 'nginx-ingress' "$NS"

         - name: Executing deploy action for ingress
           uses: ./
           with:
              namespace: ${{ env.NAMESPACE }}
              images: nginx:1.14.2
              manifests: |
                 test/integration/manifests/blue-green/test-ingress.yml
              strategy: blue-green
              route-method: ingress
              action: deploy

         - name: Checking if deployments, services and ingresses were created with green labels and original tag
           env:
              NS: ${{ env.NAMESPACE }}
           run: |
              python test/integration/k8s-deploy-test.py namespace="$NS" kind=Deployment name=nginx-deployment-green containerName=nginx:1.14.2 labels=k8s.deploy.color:green,app:nginx,workflow:actions.github.com-k8s-deploy,workflowFriendlyName:Minikube_Integration_Tests_-_blue-green_ingress selectorLabels=app:nginx,k8s.deploy.color:green
              python test/integration/k8s-deploy-test.py namespace="$NS" kind=Service name=nginx-service-green labels=k8s.deploy.color:green,workflow:actions.github.com-k8s-deploy,workflowFriendlyName:Minikube_Integration_Tests_-_blue-green_ingress selectorLabels=app:nginx,k8s.deploy.color:green
              python test/integration/k8s-deploy-test.py namespace="$NS" kind=Ingress name=nginx-ingress ingressServices=nginx-service-green,unrouted-service

         - name: Executing promote action for ingress
           uses: ./
           with:
              namespace: ${{ env.NAMESPACE }}
              images: nginx:1.14.2
              manifests: |
                 test/integration/manifests/blue-green/test-ingress.yml
              strategy: blue-green
              route-method: ingress
              action: promote

         - name: Checking if deployments, services and ingresses were created with none labels after first promote
           env:
              NS: ${{ env.NAMESPACE }}
           run: |
              python test/integration/k8s-deploy-test.py namespace="$NS" kind=Deployment name=nginx-deployment containerName=nginx:1.14.2 labels=k8s.deploy.color:None,app:nginx,workflow:actions.github.com-k8s-deploy,workflowFriendlyName:Minikube_Integration_Tests_-_blue-green_ingress selectorLabels=app:nginx,k8s.deploy.color:None
              python test/integration/k8s-deploy-test.py namespace="$NS" kind=Service name=nginx-service labels=k8s.deploy.color:None,workflow:actions.github.com-k8s-deploy,workflowFriendlyName:Minikube_Integration_Tests_-_blue-green_ingress selectorLabels=app:nginx,k8s.deploy.color:None
              python test/integration/k8s-deploy-test.py namespace="$NS" kind=Ingress name=nginx-ingress ingressServices=nginx-service,unrouted-service

         - name: Executing second deploy action for ingress with new tag
           uses: ./
           with:
              namespace: ${{ env.NAMESPACE }}
              images: nginx:latest
              manifests: |
                 test/integration/manifests/blue-green/test-ingress.yml
              strategy: blue-green
              route-method: ingress
              action: deploy

         - name: Checking if deployments (with new tag), services and ingresses were created with green labels after deploy, and old deployment persists
           env:
              NS: ${{ env.NAMESPACE }}
           run: |
              python test/integration/k8s-deploy-test.py namespace="$NS" kind=Deployment name=nginx-deployment-green containerName=nginx:latest labels=k8s.deploy.color:green,app:nginx,workflow:actions.github.com-k8s-deploy,workflowFriendlyName:Minikube_Integration_Tests_-_blue-green_ingress selectorLabels=app:nginx,k8s.deploy.color:green
              python test/integration/k8s-deploy-test.py namespace="$NS" kind=Deployment name=nginx-deployment containerName=nginx:1.14.2 labels=k8s.deploy.color:None,app:nginx,workflow:actions.github.com-k8s-deploy,workflowFriendlyName:Minikube_Integration_Tests_-_blue-green_ingress selectorLabels=app:nginx,k8s.deploy.color:None

              python test/integration/k8s-deploy-test.py namespace="$NS" kind=Service name=nginx-service-green labels=k8s.deploy.color:green,workflow:actions.github.com-k8s-deploy,workflowFriendlyName:Minikube_Integration_Tests_-_blue-green_ingress selectorLabels=app:nginx,k8s.deploy.color:green
              python test/integration/k8s-deploy-test.py namespace="$NS" kind=Service name=nginx-service labels=k8s.deploy.color:None,workflow:actions.github.com-k8s-deploy,workflowFriendlyName:Minikube_Integration_Tests_-_blue-green_ingress selectorLabels=app:nginx,k8s.deploy.color:None

              python test/integration/k8s-deploy-test.py namespace="$NS" kind=Ingress name=nginx-ingress ingressServices=nginx-service-green,unrouted-service

         - name: Executing second promote action for ingress now using new image tag
           uses: ./
           with:
              namespace: ${{ env.NAMESPACE }}
              images: nginx:latest
              manifests: |
                 test/integration/manifests/blue-green/test-ingress.yml
              strategy: blue-green
              route-method: ingress
              action: promote

         - name: Checking if deployments, services and ingresses were created with none labels after promote for new tag
           env:
              NS: ${{ env.NAMESPACE }}
           run: |
              python test/integration/k8s-deploy-test.py namespace="$NS" kind=Deployment name=nginx-deployment containerName=nginx:latest labels=k8s.deploy.color:None,app:nginx,workflow:actions.github.com-k8s-deploy,workflowFriendlyName:Minikube_Integration_Tests_-_blue-green_ingress selectorLabels=app:nginx,k8s.deploy.color:None
              python test/integration/k8s-deploy-test.py namespace="$NS" kind=Service name=nginx-service labels=k8s.deploy.color:None,workflow:actions.github.com-k8s-deploy,workflowFriendlyName:Minikube_Integration_Tests_-_blue-green_ingress selectorLabels=app:nginx,k8s.deploy.color:None
              python test/integration/k8s-deploy-test.py namespace="$NS" kind=Ingress name=nginx-ingress ingressServices=nginx-service,unrouted-service

         - name: Executing deploy action for ingress to be rejected using old tag
           uses: ./
           with:
              namespace: ${{ env.NAMESPACE }}
              images: nginx:1.14.2
              manifests: |
                 test/integration/manifests/blue-green/test-ingress.yml
              strategy: blue-green
              route-method: ingress
              action: deploy

         - name: Checking if new deployments (with old tag), services and ingresses were created with green labels after deploy, and old deployment (with latest tag) persists
           env:
              NS: ${{ env.NAMESPACE }}
           run: |
              python test/integration/k8s-deploy-test.py namespace="$NS" kind=Deployment name=nginx-deployment-green containerName=nginx:1.14.2 labels=k8s.deploy.color:green,app:nginx,workflow:actions.github.com-k8s-deploy,workflowFriendlyName:Minikube_Integration_Tests_-_blue-green_ingress selectorLabels=app:nginx,k8s.deploy.color:green
              python test/integration/k8s-deploy-test.py namespace="$NS" kind=Deployment name=nginx-deployment containerName=nginx:latest labels=k8s.deploy.color:None,app:nginx,workflow:actions.github.com-k8s-deploy,workflowFriendlyName:Minikube_Integration_Tests_-_blue-green_ingress selectorLabels=app:nginx,k8s.deploy.color:None

              python test/integration/k8s-deploy-test.py namespace="$NS" kind=Service name=nginx-service-green labels=k8s.deploy.color:green,workflow:actions.github.com-k8s-deploy,workflowFriendlyName:Minikube_Integration_Tests_-_blue-green_ingress selectorLabels=app:nginx,k8s.deploy.color:green
              python test/integration/k8s-deploy-test.py namespace="$NS" kind=Service name=nginx-service labels=k8s.deploy.color:None,workflow:actions.github.com-k8s-deploy,workflowFriendlyName:Minikube_Integration_Tests_-_blue-green_ingress selectorLabels=app:nginx,k8s.deploy.color:None

              python test/integration/k8s-deploy-test.py namespace="$NS" kind=Ingress name=nginx-ingress ingressServices=nginx-service-green,unrouted-service

         - name: Executing reject action for ingress to reject new deployment with 1.14.2 tag
           uses: ./
           with:
              namespace: ${{ env.NAMESPACE }}
              images: nginx:1.14.2
              manifests: |
                 test/integration/manifests/blue-green/test-ingress.yml
              strategy: blue-green
              route-method: ingress
              action: reject

         # MAY BE USEFUL TO ADD AN ANTI-CHECK - CHECK TO MAKE SURE CERTAIN OBJECTS DON'T EXIST
         - name: Checking if deployments, services and ingresses were created with none labels and latest tag after reject
           env:
              NS: ${{ env.NAMESPACE }}
           run: |
              python test/integration/k8s-deploy-test.py namespace="$NS" kind=Deployment name=nginx-deployment containerName=nginx:latest labels=k8s.deploy.color:None,app:nginx,workflow:actions.github.com-k8s-deploy,workflowFriendlyName:Minikube_Integration_Tests_-_blue-green_ingress selectorLabels=app:nginx,k8s.deploy.color:None
              python test/integration/k8s-deploy-test.py namespace="$NS" kind=Service name=nginx-service labels=k8s.deploy.color:None,workflow:actions.github.com-k8s-deploy,workflowFriendlyName:Minikube_Integration_Tests_-_blue-green_ingress selectorLabels=app:nginx,k8s.deploy.color:None
              python test/integration/k8s-deploy-test.py namespace="$NS" kind=Ingress name=nginx-ingress ingressServices=nginx-service,unrouted-service

         - name: Cleaning up current set up
           env:
              NS: ${{ env.NAMESPACE }}
           run: |
              python test/integration/k8s-deploy-delete.py 'Service' 'nginx-service' "$NS"
              python test/integration/k8s-deploy-delete.py 'Deployment' 'nginx-deployment' "$NS"

         - if: ${{ always() }}
           name: Delete created namespace
           env:
              NS: ${{ env.NAMESPACE }}
           run: kubectl delete ns "$NS"
